# Generated by Django 5.0.3 on 2024-03-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='publish_date_time',
            new_name='msg_date_time',
        ),
    ]
