# Generated by Django 5.0.3 on 2024-03-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orders_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_date_time',
            field=models.DateTimeField(default='2024-03-31 15:45:30+0530'),
        ),
    ]
