# Generated by Django 5.0.3 on 2024-03-31 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orders_order_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address_2',
        ),
    ]
